my:
   applicationName: "ConfigFileAtGitRepository"
   appDescription: "The configuration file is present in Git repository and this file is read by Spring Boot Config server Application"
spring:
   profiles
      active:native
  

